version: 2.1

commands:
  setup-docker:
    steps:
      - run:
          name: Setup buildx and qemu
          command: |
            sudo apt-get update
            sudo apt-get install -y qemu-user-static
            sudo apt-get install -y binfmt-support
      - run:
          name: Check versions
          command: |
            qemu-aarch64-static --version
            update-binfmts --version
      - run:
          name: Create builder
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker buildx create --name arm-builder
            docker buildx use arm-builder
            docker buildx inspect --bootstrap

jobs:
  build-docker:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    steps:
      - checkout
      - setup-docker
      - run:
          name: Connect account
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - run:
          name: Build docker images
          command: |
            DOCKER_CLI_EXPERIMENTAL=enabled docker buildx build --platform linux/amd64 --push -t "rphlo/analytics:$CIRCLE_TAG" .

workflows:
  version: 2
  build_image:
    jobs:
      - build-docker:
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
